name: Continuous deployment

on:
  push:
    branches: [main]
    paths-ignore:
      - '.devcontainer/**'
      - '.github/**'

jobs:
  call-workflow:
    permissions:
      contents: write
      id-token: write
      pages: write
    secrets: inherit
    uses: compulim/workflows/.github/workflows/continuous-deployment.yml@main
    with:
      package-name: use-state-with-ref
