extends:
  - ./.eslintrc.custom.yml
overrides:
  - env:
      commonjs: true
    files:
      - '**/*.js'
      - '**/*.ts'
    parserOptions:
      ecmaVersion: latest
    rules:
      import/no-commonjs: off
  - files:
      - '**/*.mjs'
      - '**/*.mts'
    parserOptions:
      ecmaVersion: latest
      sourceType: module
